# http://{{ .Release.Name }}-nodered.default.svc:1880
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodered
  labels:
    app: {{ .Release.Name }}-nodered
spec:
  type: NodePort
  ports:
    - port: 1880
      targetPort: 1880
      nodePort: 30880
      protocol: TCP
      name: nodered
  selector:
    app: {{ .Release.Name }}-nodered